local name, stats = ...;

LE_UNIT_STAT_STRENGTH = 1
LE_UNIT_STAT_AGILITY = 2
LE_UNIT_STAT_STAMINA = 3
LE_UNIT_STAT_INTELLECT = 4
LE_UNIT_STAT_SPIRIT = 5

COMBAT_RATING_RESILIENCE_CRIT_TAKEN = 15;
COMBAT_RATING_RESILIENCE_PLAYER_DAMAGE_TAKEN = 16;

INDEX_CLASS_NONE = 0
INDEX_CLASS_WARRIOR = 1
INDEX_CLASS_PALADIN = 2
INDEX_CLASS_HUNTER = 3
INDEX_CLASS_ROGUE = 4
INDEX_CLASS_PRIEST = 5
INDEX_CLASS_DEATH_KNIGHT = 6
INDEX_CLASS_SHAMAN = 7
INDEX_CLASS_MAGE = 8
INDEX_CLASS_WARLOCK = 9
INDEX_CLASS_DRUID = 11

CLASS_STATS_ALL = {
    "HEALTH",
    "POWER"
}

CLASS_STATS = {
    [INDEX_CLASS_WARRIOR] = {
        "STAMINA",
        "STRENGTH",
        "AGILITY",
    },
    [INDEX_CLASS_PALADIN] = {
        "STRENGTH",
        "STAMINA",
        "AGILITY",
    },
    [INDEX_CLASS_HUNTER] = {
        "STAMINA",
        "AGILITY",
    },
    [INDEX_CLASS_ROGUE] = {
        "STAMINA",
        "AGILITY",
    },
    [INDEX_CLASS_PRIEST] = {
        "INTELLECT",
        "SPIRIT",
    },
    [INDEX_CLASS_DEATH_KNIGHT] = {
        "STRENGTH",
        "STAMINA",
    },
    [INDEX_CLASS_SHAMAN] = {
        "AGILITY",
        "INTELLECT",
        "SPIRIT",
    },
    [INDEX_CLASS_MAGE] = {
        "INTELLECT",
        "SPIRIT",
    },
    [INDEX_CLASS_WARLOCK] = {
        "STAMINA",
        "INTELLECT",
        "SPIRIT",
    },
    [INDEX_CLASS_DRUID] = {
        "STAMINA",
        "STRENGTH",
        "AGILITY",
        "INTELLECT",
        "SPIRIT",
    },
}